spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/micautorization
    username: ${POSTGRES_AUTH_USER}
    password: ${POSTGRES_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
