spring:
  application:
    name: mic-authserver
  profiles:
    active: ${PROFILE:local}

server:
  port: 9001

nexaplaform:
  openapi:
    scan-package: com.nexaplaform.authserver.app.api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: false
  show-oauth2-endpoints: false